### ISSUE TITLE
要一起修改下么

### ISSUE THREAD

**Issue by Hi-Rube** [ShinCurry/PHPShelf#1]

**Comment by XerWandeRer** [comment]
请问 [`config.inc.php`](https://github.com/ShinCurry/PHPShelf/blob/master/includes/config.inc.php) 中的第二行：

``` php
$json = file_get_contents(dirname(__FILE__) . "/../config.json");
```

引用项目根目录下的 `config.json` 文件有没有更好的写法？

**Comment by Hi-Rube** [comment]
@XerWandeRer 你想要如何更好，for example 路径什么的

**Comment by XerWandeRer** [comment]
写成相对路径呀：

``` php
$json = file_get_contents("../config.json");
```

为什么这样会报错？

**Comment by Hi-Rube** [comment]
@XerWandeRer 因为路径不对啊，，，好的做法是这是一个常量来表示配置文件的根路径，比如CONFIG_ROOT = "/home/XerwandeRer/PHP/SYSTEM/Config"  
然后 

```
  $json = file_get_contents(CONFIG_ROOT + "/config.json");
```

这是我认为好的~~

**Comment by XerWandeRer** [comment]
`"../config.json"` 的路径应该是正确的啊，参见 [`inputcheck.php`](https://github.com/ShinCurry/PHPShelf/blob/master/includes/inputcheck.php) 的第二行：

``` php
include ('./config.inc.php');
```

其中引用同目录下的 `config.inc.php` 文件也是用了类似相对路径写法。

**Comment by Hi-Rube** [comment]
@XerWandeRer 引用和文件读取不一样额~~，  include是可以设路径的 http://blog.csdn.net/oyd/article/details/2030293

**Comment by XerWandeRer** [comment]
@Hi-Rube 受教了~ 谢谢！

**Comment by Hi-Rube** [comment]
大晚上的就等你回复呢~~ 睡觉了 @XerWandeRer

**Comment by XerWandeRer** [comment]
@Hi-Rube 哈… 不好意思了。

**Comment by shincurry** [comment]
@Hi-Rube 用一个常量来表示配置文件的根路径就意味着每一个要用这项目的人都要自己改一次？
而且这样的话不能放在 json 里面就要写进 php 文件
「所以说我闲着蛋疼的用 json 存参数其实完全可以直接用 php 文件存？」
@XerWandeRer 你个死强迫症 2333

**Comment by Hi-Rube** [comment]
@ShinCurry  不用自己改一次啊~  因为类似/home/XerwandeRer/PHP 这样的路径是有函数可以获取的 额~

**Comment by shincurry** [comment]
是这个吧，之前试过的，后来还是用了提交的那种。

``` php
$_SERVER['DOCUMENT_ROOT']
```
